from models.llama_layer import CustomLlamaForCausalLM as ClusterLayerLlamaForCausalLM
from models.mistral_layer import CustomMistralForCausalLM as ClusterLayerMistralForCausalLM
from models.opt_layer import CustomOPTForCausalLM as ClusterLayerOPTForCausalLM